[package]
name = "tantabus"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cozy-chess = { path = "../../cozy-chess/cozy-chess" }
arrayvec = "0.7"
